# Generated by Django 5.2.9 on 2026-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aas_integration', '0002_remove_idta_import_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aasconnection',
            name='aas_id_field',
            field=models.CharField(blank=True, max_length=100),
        ),

        migrations.AddField(
            model_name='aasconnection',
            name='aas_link',
            field=models.CharField(blank=True, max_length=100),
        ),

        migrations.AddField(
            model_name='aasconnection',
            name='aas_ui_url',
            field=models.CharField(blank=True, max_length=255),
            preserve_default=False,
        ),
    ]
