# Generated by Django 5.2.9 on 2026-06-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aas_integration', '0004_hierarchy_template'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submodelelement',
            options={'ordering': ['template', 'order', 'id_short']},
        ),
        migrations.RemoveConstraint(
            model_name='entitytypeconfiguration',
            name='aas_integration_entitytypeconfiguration_unique_type',
        ),
        migrations.RemoveConstraint(
            model_name='submodelconfiguration',
            name='aas_integration_submodelconfiguration_unique_config',
        ),
        migrations.AlterUniqueTogether(
            name='entitytypeconfiguration',
            unique_together={('connection', 'content_type')},
        ),
        migrations.AlterUniqueTogether(
            name='submodelconfiguration',
            unique_together={('connection', 'entity_type', 'template')},
        ),
    ]
